api_platform:
    keep_legacy_inflector: false
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        yaml: [ 'application/x-yaml' ]
        csv: [ 'text/csv' ]
    title: TBD
    version: 1.0.0
    # Good cache defaults for REST APIs
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalizationContext:
            skip_null_values: false
        denormalizationContext:
            allow_extra_attributes: false
        extra_properties:
            standard_put: false
