swagger_ui:
    path: /docs
    controller: api_platform.swagger_ui.action

api_login_check:
    path: '%app.security.api_route%/login_check'
    methods: [ 'POST' ]

api_refresh_token:
    path: '%app.security.api_route%/token_refresh'
    methods: [ 'POST' ]
    
api_token_invalidate:
    path: '%app.security.api_route%/token_invalidate'
